apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: telegraf-ds
data:
  telegraf.conf: |+
    [agent]
      interval = "60s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "60s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      quiet = false
      logfile = ""
      hostname = "$HOSTNAME"
      omit_hostname = false
    [[outputs.influxdb]]
      urls = ["http://192.168.66.56:8086"]
      database = "telegraf"
      retention_policy = "2w"
      write_consistency = "any"
      timeout = "5s"
      user_agent = "telegraf"
      insecure_skip_verify = false
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = true
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs"]
    [[inputs.diskio]]
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      container_names = []
      timeout = "5s"
      perdevice = true
      total = false
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.system]]
    [[inputs.exec]]
      commands = [ "/opt/vc/bin/vcgencmd measure_temp" ]
      name_override = "cpu_temperature"
      data_format = "grok"
      grok_patterns = ["%{NUMBER:value:float}"]
    [[inputs.exec]]
      commands = [ "/opt/vc/bin/vcgencmd measure_clock arm" ]
      name_override = "cpu_frequency"
      data_format = "grok"
      grok_patterns = ["%{FREQUENCY:freq:int}"]
      grok_custom_patterns = 'FREQUENCY [0-9]{9,10}'
